stages:
  - test
  - build
  - deploy

cache:
  paths:
    - frontend/node_modules/

test:
  stage: test
  script:
    - cd frontend
    - npm install
    - cd ..
build:
  stage : build
  script:    
    - cd frontend
    - rm -rf .env.production
    - cp .env.production.example .env.production  
    - npm run build   
    - cd .. 
deploy:
  stage : deploy
  artifacts:
    paths:
      - frontend/dist
  only :
    - master
  script:    
    - ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "mkdir $SSH_PATH/siakad_temp"
    - scp -P $SSH_PORT -rp frontend/dist/* $SSH_USERNAME@$SSH_HOST:$SSH_PATH/siakad_temp
    - scp -P $SSH_PORT -rp frontend/dist/.htaccess $SSH_USERNAME@$SSH_HOST:$SSH_PATH/siakad_temp
    - ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "mv $SSH_PATH/siakad $SSH_PATH/siakad_old && mv $SSH_PATH/siakad_temp $SSH_PATH/siakad"
    - ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "rm -rf $SSH_PATH/siakad_old"
