stages:
  - test
  - build
  - deploy

cache:
  paths:
    - frontend/node_modules/

test:
  stage: test
  script:
    - cd frontend
    - npm install
    - cd ..
build:
  stage : build
  script:    
    - cd frontend  
    - npm run build   
    - cd .. 
deploy:
  stage : deploy
  artifacts:
    paths:
      - frontend/dist
  only :
    - master
  script:
    - echo "DEPLOY"
    - (echo "$SSH_USERNAME@$SSH_HOST")
