before_script:
  - cd frontend
  - npm install
  - cd ..
stages:
  - build
  - stage_deploy

build:
  stage : build
  script:
    - echo "Building"  
    - cd frontend  
    - npm run build    
stage_deploy:
  artifacts:
    paths:
      - dist
  only :
    - master
  script:
    - echo "DEPLOY"
    - (echo "$SSH_USERNAME@$SSH_HOST")
