stages:
  - build
  - deploy

build:
  stage : build
  script:
    - echo "Building"  
    - cd frontend  
deploy:
  stage : deploy
  artifacts:
    paths:
      - dist
  only :
    - master
  script:
    - echo "DEPLOY"
    - pwd
    - (echo "$SSH_USERNAME@$SSH_HOST")
